import api from './api'
import type { Charger, Gun, Pedestal } from '@/types/charger'
import { getChargerGuns } from '@/types/charger'
export type { Charger, Gun, Pedestal }

// User Management
export interface User {
  id: string
  firstName: string
  lastName: string
  email: string
  phone: string
  role: string
  userType: string
  imageUrl?: string
  avatar?: string
  profilePicture?: string
  picture?: string
  isVerified: boolean
  isActive: boolean
  isTrainee?: boolean
  autofillEnabled?: boolean
  operatorAirtableId?: string
  organizationId?: string | null
  /** Cross-org admin directory: the user's organizations (legacy + memberships). */
  organizations?: { id: string; name: string }[]
  createdAt: string
  updatedAt: string
}

export interface UserUpdateData {
  firstName?: string
  lastName?: string
  email?: string
  phone?: string
  role?: string
  userType?: string
  isVerified?: boolean
  isActive?: boolean
  isTrainee?: boolean
  autofillEnabled?: boolean
  operatorAirtableId?: string
  organizationId?: string | null
}

// Admin operator with full profile (from GET /api/admin/operators)
export interface AdminOperator {
  id: string
  firstName: string
  lastName: string
  email: string
  phone: string | null
  cashierId: string | null
  isTrainee: boolean
  autofillEnabled: boolean
  isVerified: boolean
  createdAt: string
}

// Charger Management – Charger, Gun, Pedestal from @/types/charger

export interface GunCreateData {
  name?: string
  pedestalId?: string
  gunNumber?: string
  citrineConnectorId?: string
}

export interface GunUpdateData {
  name?: string
  citrineConnectorId?: string
  gunNumber?: string
}

export interface GunStatusUpdateData {
  chargingStatus: 'IN_USE' | 'AVAILABLE' | 'UNDER_MAINTENANCE'
  currentSessionId?: string
}

/** Create charger: only power required; kabisaId is generated by backend */
export interface ChargerCreateData {
  power: number
  meterId?: string
  gunNumber?: string
  latitude?: number
  longitude?: number
  name?: string
  address?: string
  momoCode?: string
  imageUrl?: string
  ownerName?: string
  generateEbm?: boolean
  hasTwoMeters?: boolean
  pricePerKwh?: number
  ownerPhone?: string
  ownerEmail?: string
  ownerWebsite?: string
}

/** Update charger: same as create + operationalStatus. Nullable fields can be cleared by sending null. */
export interface ChargerUpdateData extends Omit<Partial<ChargerCreateData>, 'pricePerKwh' | 'ownerPhone' | 'ownerEmail' | 'ownerWebsite'> {
  operationalStatus?: 'OPERATIONAL' | 'UNDER_REPAIR' | 'CLOSED' | 'CANCELLED' | 'BEING_INSTALLED' | 'PLANNED_FOR_FUTURE_DATE'
  generateEbm?: boolean
  hasTwoMeters?: boolean
  pricePerKwh?: number | null
  ownerPhone?: string | null
  ownerEmail?: string | null
  ownerWebsite?: string | null
}

export interface PedestalCreateData {
  name?: string
  onlineStatus?: 'OFFLINE' | 'ONLINE'
  citrineChargerId?: string
}

export interface PedestalUpdateData {
  name?: string
  onlineStatus?: 'OFFLINE' | 'ONLINE'
  citrineChargerId?: string
}

export interface MeterCreateData {
  meterName?: string
  meterNumber?: string
}

export interface Meter {
  id: string
  kabisaId: string
  meterName?: string
  meterNumber?: string
  isActive: boolean
  createdAt: string
  updatedAt: string
}

// Shop Management - uses IShopVehicle/ShopOrder from types/shop.ts for full types
import { IShopVehicle, ShopOrder } from '@/types/shop'

export type { ShopOrder }

export interface ShopVehicleCreateData {
  shopId: string
  make: string
  model: string
  year: number
  trim?: string[]
  category: 'PASSENGER' | 'COMMERCIAL'
  classification: 'SEDAN' | 'COMPACT_SUV' | 'SUV' | 'PICKUP' | 'VAN' | 'LIGHT_DUTY_TRUCK' | 'TRUCK' | 'REFRIGERATED' | 'BUS'
  kabisaProduct: 'CORE' | 'NON_CORE' | 'OTHERS' | 'ALTERNATIVE'
  range: number
  price: number
  currency?: string
  optionalExtras?: string[]
  doors: number
  seats: number
  storageCapacity: number
  storageCapacityUnit?: string
  details: string
  mainImage: string
  orderImage?: string
  additionalImages?: string[]
  batteryCapacity: number
  availableColors: { color: string; imageUrl: string }[]
  country?: string
}

export interface AdminSessionTransaction {
  id: string
  transactionId?: string | null
  transactionStatus: 'PENDING' | 'SUCCESS' | 'FAILED' | 'CANCELLED' | string
  transactionType?: string
  amount?: number | null
  currency?: string
  transactionDate?: string
  externalTransactionReference?: string | null
  momoExternalId?: string | null
  paymentMethod?: {
    paymentMethodType?: string | null
    momoNumber?: string | null
  } | null
}

export interface AdminSessionEbm {
  id: string
  cisInvoiceNumber?: number | null
  receiptNumber?: number | null
  salesTypeCode?: string | null
  receiptTypeCode?: string | null
  paymentMethodCode?: string | null
  paymentMethodName?: string | null
  phoneForEbm?: string | null
  vsdcReceiptPublicationDate?: string | null
}

// Charging Sessions (Admin View) - Updated with payment method fields
export interface AdminSession {
  id: string
  sessionId: string
  vehicleId: string
  operatorId: string
  chargerId: string
  source?: 'MANUAL' | 'REMOTE'
  startSoc: number
  endSoc: number | null
  chargedKwh: number | null
  startTime: string
  endTime: string | null
  sessionStatus: 'STARTED' | 'PAUSED' | 'COMPLETED' | 'CANCELLED' | 'PAID' | 'EBM_ISSUED' | 'REFUNDED'
  totalAmount: number | null
  createdAt: string
  updatedAt: string
  isPaid?: boolean
  paymentMethodName?: string
  paymentMethodEnum?: 'MOMO' | 'MOMO_CODE_PAYMENT' | 'FREE_ALLOWANCE' | 'CONTRACT' | 'CARD'
  discountRate?: number
  discountAmount?: number
  supplyAmount?: number
  hasDiscount?: boolean
  hasCompletedSaleEbm?: boolean
  hasCompletedNormalEbm?: boolean
  hasCompletedRefundEbm?: boolean
  customerName?: string | null
  customerPhone?: string | null
  ebmTin?: string | null
  description?: string | null
  cancellationReason?: string | null
  commonSessionTag?: string | null
  customerInfoAdded?: boolean
  carModelMake?: string | null
  transactions?: AdminSessionTransaction[]
  ebms?: AdminSessionEbm[]
  vehicle?: {
    id: string
    kabisaId: string
    model: string
    make: string
    licensePlates?: Array<{
      id: string
      licencePlateNumber: string
      isActive?: boolean
    }>
  }
  operator?: {
    id: string
    firstName: string
    lastName: string
    email: string
  }
  charger?: {
    id: string
    name: string
    kabisaId: string
  }
  gun?: {
    id?: string
    name?: string | null
  }
  pedestal?: {
    id?: string
    name?: string | null
  }
}

// ===== USER MANAGEMENT APIs =====

export interface UserCreateData {
  firstName: string
  lastName: string
  email?: string
  phone?: string
  role: string
  userType?: string
  organizationId?: string | null
  isVerified?: boolean
}

// Create user (admin)
export const createUserAdmin = async (data: UserCreateData): Promise<{ status: string; message: string; data: { user: User } }> => {
  try {
    const response = await api().post('/api/admin/users', data)
    if (response.data.status === 'error') throw new Error(response.data.message)
    return response.data
  } catch (error) {
    console.error('Error in createUserAdmin:', error)
    throw error
  }
}

export interface UsersPagination { page: number; limit: number; total: number; totalPages: number }
export interface GetAllUsersParams { page?: number; limit?: number; search?: string; role?: string; organizationId?: string }
export interface AdminUsersResponse { status: string; message: string; data: { users: User[]; pagination?: UsersPagination } }

// Get admin users. With no `page` the backend returns the full set (no
// pagination block); pass `page` for a server-paginated slice. role /
// organizationId filter server-side (KAB-177).
export const getAdminUsers = async (params: GetAllUsersParams = {}): Promise<AdminUsersResponse> => {
  try {
    const q = new URLSearchParams()
    if (params.page != null) q.set('page', String(params.page))
    if (params.limit != null) q.set('limit', String(params.limit))
    if (params.search) q.set('search', params.search)
    if (params.role) q.set('role', params.role)
    if (params.organizationId) q.set('organizationId', params.organizationId)
    const qs = q.toString()
    const response = await api().get(`/api/admin/users${qs ? `?${qs}` : ''}`)

    if (response.data.status === 'error') {
      throw new Error(response.data.message)
    }

    return response.data
  } catch (error) {
    console.error('🔍 Admin - Error in getAdminUsers:', error)
    throw error
  }
}

// Back-compat no-arg full fetch — existing shift/dashboard consumers reference
// this directly as a React Query queryFn, so it must take no arguments.
export const getAllUsers = (): Promise<AdminUsersResponse> => getAdminUsers()

// Get blocked users
export const getBlockedUsers = async (): Promise<{ status: string; message: string; data: { users: User[] } }> => {
  try {
    const response = await api().get('/api/admin/users/blocked')
    
    if (response.data.status === 'error') {
      throw new Error(response.data.message)
    }
    
    return response.data
  } catch (error) {
    console.error('🔍 Admin - Error in getBlockedUsers:', error)
    throw error
  }
}

// Get user details
export const getUserDetails = async (userId: string): Promise<{ status: string; message: string; data: { user: User } }> => {
  try {
    const response = await api().get(`/api/admin/users/${userId}`)
    
    if (response.data.status === 'error') {
      throw new Error(response.data.message)
    }
    
    return response.data
  } catch (error) {
    console.error('🔍 Admin - Error in getUserDetails:', error)
    throw error
  }
}

// Update user
export const updateUser = async (userId: string, data: UserUpdateData): Promise<{ status: string; message: string; data: { user: User } }> => {
  try {
    const response = await api().put(`/api/admin/users/${userId}`, data)
    
    if (response.data.status === 'error') {
      throw new Error(response.data.message)
    }
    
    return response.data
  } catch (error) {
    console.error('🔍 Admin - Error in updateUser:', error)
    throw error
  }
}

// Verify user
export const verifyUser = async (userId: string): Promise<{ status: string; message: string }> => {
  try {
    const response = await api().post(`/api/admin/users/${userId}/verify`)
    
    if (response.data.status === 'error') {
      throw new Error(response.data.message)
    }
    
    return response.data
  } catch (error) {
    console.error('🔍 Admin - Error in verifyUser:', error)
    throw error
  }
}

// Block user
export const blockUser = async (userId: string): Promise<{ status: string; message: string }> => {
  try {
    const response = await api().post(`/api/admin/users/${userId}/block`)
    
    if (response.data.status === 'error') {
      throw new Error(response.data.message)
    }
    
    return response.data
  } catch (error) {
    console.error('🔍 Admin - Error in blockUser:', error)
    throw error
  }
}

// Unblock user
export const unblockUser = async (userId: string): Promise<{ status: string; message: string }> => {
  try {
    const response = await api().post(`/api/admin/users/${userId}/unblock`)
    
    if (response.data.status === 'error') {
      throw new Error(response.data.message)
    }
    
    return response.data
  } catch (error) {
    console.error('🔍 Admin - Error in unblockUser:', error)
    throw error
  }
}

/** OrgMembership role — distinct from the global User.role. */
export type OrgMembershipRole = 'ORG_OWNER' | 'ORG_ADMIN' | 'FINANCE' | 'OPERATOR' | 'VIEWER'
export type OrgMembershipStatus = 'ACTIVE' | 'SUSPENDED'

// Add an organization to a user (platform-admin) — creates/reactivates an org membership
export const addUserOrganization = async (userId: string, orgId: string, role?: OrgMembershipRole): Promise<{ status: string; message: string; data: { user: User } }> => {
  try {
    const response = await api().post(`/api/admin/users/${userId}/organizations`, { orgId, ...(role && { role }) })
    if (response.data.status === 'error') throw new Error(response.data.message)
    return response.data
  } catch (error) {
    console.error('🔍 Admin - Error in addUserOrganization:', error)
    throw error
  }
}

// Change a user's membership role/status (platform-admin)
export const changeUserOrganization = async (userId: string, orgId: string, data: { role?: OrgMembershipRole; status?: OrgMembershipStatus }): Promise<{ status: string; message: string; data: { user: User } }> => {
  try {
    const response = await api().patch(`/api/admin/users/${userId}/organizations/${orgId}`, data)
    if (response.data.status === 'error') throw new Error(response.data.message)
    return response.data
  } catch (error) {
    console.error('🔍 Admin - Error in changeUserOrganization:', error)
    throw error
  }
}

// Remove an organization from a user (platform-admin) — suspends the membership / clears the home org
export const removeUserOrganization = async (userId: string, orgId: string): Promise<{ status: string; message: string; data: { user: User } }> => {
  try {
    const response = await api().delete(`/api/admin/users/${userId}/organizations/${orgId}`)
    if (response.data.status === 'error') throw new Error(response.data.message)
    return response.data
  } catch (error) {
    console.error('🔍 Admin - Error in removeUserOrganization:', error)
    throw error
  }
}

// Get all active operators with trainee status
export const getOperators = async (): Promise<{ status: string; message: string; data: { operators: AdminOperator[] } }> => {
  try {
    const response = await api().get('/api/admin/operators')

    if (response.data.status === 'error') {
      throw new Error(response.data.message)
    }

    return response.data
  } catch (error) {
    console.error('🔍 Admin - Error in getOperators:', error)
    throw error
  }
}

// Set or unset trainee status for an operator
export const patchOperatorTrainee = async (
  operatorId: string,
  isTrainee: boolean
): Promise<{ status: string; message: string; data: { user: User } }> => {
  try {
    const response = await api().patch(`/api/admin/operators/${operatorId}/trainee`, { isTrainee })

    if (response.data.status === 'error') {
      throw new Error(response.data.message)
    }

    return response.data
  } catch (error) {
    console.error('🔍 Admin - Error in patchOperatorTrainee:', error)
    throw error
  }
}

// Set or unset autofill status for an operator
export const patchOperatorAutofill = async (
  operatorId: string,
  autofillEnabled: boolean
): Promise<{ status: string; message: string; data: { user: User } }> => {
  try {
    const response = await api().patch(`/api/admin/operators/${operatorId}/autofill`, { autofillEnabled })

    if (response.data.status === 'error') {
      throw new Error(response.data.message)
    }

    return response.data
  } catch (error) {
    console.error('Admin - Error in patchOperatorAutofill:', error)
    throw error
  }
}

// ===== CHARGER MANAGEMENT APIs =====

// Get all chargers
export const getAllChargers = async (): Promise<{ status: string; message: string; data: { chargers: Charger[] } }> => {
  try {
    const response = await api().get('/api/chargers')
    
    if (response.data.status === 'error') {
      throw new Error(response.data.message)
    }
    
    return response.data
  } catch (error) {
    console.error('🔍 Admin - Error in getAllChargers:', error)
    throw error
  }
}

// Create charger
export const createCharger = async (data: ChargerCreateData): Promise<{ status: string; message: string; data: { charger: Charger } }> => {
  try {
    const response = await api().post('/api/chargers', data)
    
    if (response.data.status === 'error') {
      throw new Error(response.data.message)
    }
    
    return response.data
  } catch (error) {
    console.error('🔍 Admin - Error in createCharger:', error)
    throw error
  }
}

// Update charger
export const updateCharger = async (chargerId: string, data: ChargerUpdateData): Promise<{ status: string; message: string; data: { charger: Charger } }> => {
  try {
    const response = await api().put(`/api/chargers/${chargerId}`, data)
    
    if (response.data.status === 'error') {
      throw new Error(response.data.message)
    }
    
    return response.data
  } catch (error) {
    console.error('🔍 Admin - Error in updateCharger:', error)
    throw error
  }
}

// Delete charger
export const deleteCharger = async (chargerId: string): Promise<{ status: string; message: string }> => {
  try {
    const response = await api().delete(`/api/chargers/${chargerId}`)
    
    if (response.data.status === 'error') {
      throw new Error(response.data.message)
    }
    
    return response.data
  } catch (error) {
    console.error('🔍 Admin - Error in deleteCharger:', error)
    throw error
  }
}

// ===== SHOP MANAGEMENT APIs =====

// Get shop vehicles
export const getShopVehicles = async (): Promise<{ status: string; message: string; data: { shopVehicles: IShopVehicle[] } }> => {
  try {
    const response = await api().get('/api/admin/shop/vehicles')
    
    if (response.data.status === 'error') {
      throw new Error(response.data.message)
    }
    
    return response.data
  } catch (error) {
    console.error('🔍 Admin - Error in getShopVehicles:', error)
    throw error
  }
}

// Create shop vehicle
export const createShopVehicle = async (data: ShopVehicleCreateData): Promise<{ status: string; message: string; data: { shopVehicle: IShopVehicle } }> => {
  try {
    const response = await api().post('/api/admin/shop/vehicles', data)
    
    if (response.data.status === 'error') {
      throw new Error(response.data.message)
    }
    
    return response.data
  } catch (error) {
    console.error('🔍 Admin - Error in createShopVehicle:', error)
    throw error
  }
}

// Update shop vehicle
export const updateShopVehicle = async (vehicleId: string, data: Partial<ShopVehicleCreateData>): Promise<{ status: string; message: string; data: { shopVehicle: IShopVehicle } }> => {
  try {
    const response = await api().put(`/api/admin/shop/vehicles/${vehicleId}`, data)
    
    if (response.data.status === 'error') {
      throw new Error(response.data.message)
    }
    
    return response.data
  } catch (error) {
    console.error('🔍 Admin - Error in updateShopVehicle:', error)
    throw error
  }
}

// Delete shop vehicle
export const deleteShopVehicle = async (vehicleId: string): Promise<{ status: string; message: string }> => {
  try {
    const response = await api().delete(`/api/admin/shop/vehicles/${vehicleId}`)
    
    if (response.data.status === 'error') {
      throw new Error(response.data.message)
    }
    
    return response.data
  } catch (error) {
    console.error('🔍 Admin - Error in deleteShopVehicle:', error)
    throw error
  }
}

// Get shop orders (backend returns them under `shopOrders`)
export const getShopOrders = async (): Promise<{ status: string; message: string; data: { shopOrders: ShopOrder[] } }> => {
  try {
    const response = await api().get('/api/admin/shop/orders')
    
    if (response.data.status === 'error') {
      throw new Error(response.data.message)
    }
    
    return response.data
  } catch (error) {
    console.error('🔍 Admin - Error in getShopOrders:', error)
    throw error
  }
}

// Update shop order
export const updateShopOrder = async (orderId: string, data: Partial<ShopOrder>): Promise<{ status: string; message: string; data: { order: ShopOrder } }> => {
  try {
    const response = await api().put(`/api/admin/shop/orders/${orderId}`, data)

    if (response.data.status === 'error') {
      throw new Error(response.data.message)
    }

    return response.data
  } catch (error) {
    console.error('🔍 Admin - Error in updateShopOrder:', error)
    throw error
  }
}

// Update shop order status (PENDING → CONFIRMED → COMPLETED, or CANCELLED)
export const updateShopOrderStatus = async (orderId: string, orderStatus: ShopOrder['status']): Promise<{ status: string; message: string; data: { shopOrder: ShopOrder } }> => {
  try {
    const response = await api().put(`/api/admin/shop/orders/${orderId}/status`, { orderStatus })
    if (response.data.status === 'error') {
      throw new Error(response.data.message)
    }
    return response.data
  } catch (error) {
    console.error('🔍 Admin - Error in updateShopOrderStatus:', error)
    throw error
  }
}

// ===== CHARGING SESSIONS (ADMIN VIEW) APIs =====

type SessionListParams = {
  page?: number
  limit?: number
  search?: string
  status?: string
  organizationId?: string
  /** Exact-match filter on the human-readable sessionId. Used by share-link
   *  auto-open so we never pick a false positive from the free-text `search`. */
  sessionId?: string
  /** Restrict to the charging sessions that belong to a given shift report
   *  (OperatorShiftReport id). Resolved server-side to the report's operator +
   *  check-in/out window. Used by the "View sessions" button on Shift Details. */
  shiftReportId?: string
  /** ISO date string — only sessions with startTime >= this value */
  startDate?: string
  /** ISO date string — only sessions with startTime <= this value */
  endDate?: string
}

function buildSessionQueryString(params?: SessionListParams): string {
  const queryParams = new URLSearchParams()
  if (params?.page) queryParams.append('page', params.page.toString())
  if (params?.limit) queryParams.append('limit', params.limit.toString())
  if (params?.search) queryParams.append('search', params.search)
  if (params?.status && params.status !== 'all') queryParams.append('status', params.status)
  if (params?.organizationId) queryParams.append('organizationId', params.organizationId)
  if (params?.sessionId) queryParams.append('sessionId', params.sessionId)
  if (params?.shiftReportId) queryParams.append('shiftReportId', params.shiftReportId)
  if (params?.startDate) queryParams.append('startDate', params.startDate)
  if (params?.endDate) queryParams.append('endDate', params.endDate)
  const qs = queryParams.toString()
  return qs ? `?${qs}` : ''
}

// Get all sessions (admin view)
export const getAllSessions = async (
  params?: SessionListParams
): Promise<{ status: string; message: string; data: { sessions: AdminSession[]; pagination: any } }> => {
  try {
    const response = await api().get(`/api/charging-sessions/admin/all-sessions${buildSessionQueryString(params)}`)
    
    if (response.data.status === 'error') {
      throw new Error(response.data.message)
    }
    
    return response.data
  } catch (error) {
    console.error('🔍 Admin - Error in getAllSessions:', error)
    throw error
  }
}

// Get active sessions (admin view)
export const getActiveSessions = async (
  params?: SessionListParams
): Promise<{ status: string; message: string; data: { sessions: AdminSession[]; pagination: any } }> => {
  try {
    const response = await api().get(`/api/charging-sessions/admin/active-sessions${buildSessionQueryString(params)}`)
    
    if (response.data.status === 'error') {
      throw new Error(response.data.message)
    }
    
    return response.data
  } catch (error) {
    console.error('🔍 Admin - Error in getActiveSessions:', error)
    throw error
  }
}

export interface AdminSessionStats {
  totalSessions: number
  completedSessions: number
  cancelledSessions: number
  activeSessions: number
  totalRevenue: number
  totalKwh: number
  completionRate: number
}

// Get aggregated session stats without loading rows (server-side groupBy+aggregate)
export const getAdminSessionStats = async (params?: { startDate?: string; endDate?: string }): Promise<{ status: string; message: string; data: { stats: AdminSessionStats } }> => {
  try {
    const queryParams = new URLSearchParams()
    if (params?.startDate) queryParams.append('startDate', params.startDate)
    if (params?.endDate) queryParams.append('endDate', params.endDate)
    const qs = queryParams.toString()
    const response = await api().get(`/api/charging-sessions/admin/stats${qs ? `?${qs}` : ''}`)
    if (response.data.status === 'error') throw new Error(response.data.message)
    return response.data
  } catch (error) {
    console.error('Admin - Error in getAdminSessionStats:', error)
    throw error
  }
}

// Update charging session (admin only)
export interface UpdateSessionData {
  startSoc?: number
  endSoc?: number
  chargedKwh?: number
  startTime?: string
  endTime?: string
  customerName?: string | null
  carModelMake?: string | null
  imageUrl?: string | null
  chargerScreen?: string | null
  odometerReading?: number
  odometerReadingImage?: string | null
  ratePerKwh?: number
  discountRate?: number
  discountAmount?: number
  forceInvoicedCustomer?: boolean
  // KAB-146: relink/create the linked vehicle by plate, re-run the pricing
  // engine, attach an optional payment proof, and record an audit reason.
  licensePlate?: string
  recalculate?: boolean
  paymentProofUrl?: string
  reason?: string
  skipEbmRefund?: boolean
}

export interface SessionAuditChange {
  field: string
  from: string | number | boolean | null
  to: string | number | boolean | null
}

export interface SessionEditReconciliation {
  ebmRefunded: boolean
  ebmReissued: boolean
  ebmSkipped?: boolean
  paymentMethod: string | null
  warning?: string
  // True when a prior real MOMO payment was kept (superseded) and a new method recorded.
  supersededMomo?: boolean
}

export const updateChargingSession = async (
  sessionId: string,
  data: UpdateSessionData
): Promise<{ status: string; message: string; data: { session: AdminSession; reconciliation?: SessionEditReconciliation; changes?: SessionAuditChange[] } }> => {
  try {
    const response = await api().patch(`/api/charging-sessions/${sessionId}`, data)

    if (response.data.status === 'error') {
      throw new Error(response.data.message)
    }

    return response.data
  } catch (error: any) {
    console.error('🔍 Admin - Error in updateChargingSession:', error)
    throw new Error(error.response?.data?.message || error.message || 'Failed to update session')
  }
}

// KAB-146: dry-run preview of an admin session edit (recalculation + resolved vehicle)
export interface PreviewSessionEditData {
  licensePlate?: string
  chargedKwh?: number
  discountRate?: number
  discountAmount?: number
  recalculate?: boolean
}

export interface SessionEditPreview {
  current: {
    licensePlate: string | null
    chargedKwh: number | null
    ratePerKwh: number | null
    totalAmount: number | null
    sessionStatus: string
    paymentMethod: string | null
  }
  updated: {
    licensePlate: string | null
    chargedKwh: number
    ratePerKwh: number
    baseAmount: number
    discountRate: number | null
    discountAmount: number | null
    totalAmount: number
    userType: string
    currency: string
    isInvoicedCustomer: boolean
  }
  vehicle: { willCreate: boolean; existing: { id: string; make: string | null; model: string | null } | null }
  amountChanged: boolean
  requiresEbmRefund: boolean
}

export const previewSessionEdit = async (
  sessionId: string,
  data: PreviewSessionEditData
): Promise<{ status: string; message: string; data: SessionEditPreview }> => {
  try {
    const response = await api().post(`/api/charging-sessions/${sessionId}/admin-edit/preview`, data)
    if (response.data.status === 'error') {
      throw new Error(response.data.message)
    }
    return response.data
  } catch (error: any) {
    console.error('🔍 Admin - Error in previewSessionEdit:', error)
    throw new Error(error.response?.data?.message || error.message || 'Failed to preview edit')
  }
}

// KAB-146: admin payment-status transitions
export type SessionPaymentMethod = 'MOMO' | 'MOMO_CODE_PAYMENT' | 'CARD' | 'CONTRACT' | 'FREE_ALLOWANCE' | 'KABISA'

export interface SetPaymentStatusData {
  status: 'PAID' | 'UNPAID' | 'EBM_ISSUED'
  paymentMethod?: SessionPaymentMethod
  phone?: string
  proofUrl?: string
  reason?: string
  skipEbmRefund?: boolean
  // When marking FREE_ALLOWANCE and the plate has no allowance, mint + consume one.
  createFreeAllowance?: boolean
}

export const setSessionPaymentStatus = async (
  sessionId: string,
  data: SetPaymentStatusData
): Promise<{ status: string; message: string; data: { session?: AdminSession | null; reconciliation?: SessionEditReconciliation; paymentResult?: unknown } }> => {
  try {
    const response = await api().post(`/api/charging-sessions/${sessionId}/payment-status`, data)
    if (response.data.status === 'error') {
      throw new Error(response.data.message)
    }
    return response.data
  } catch (error: any) {
    console.error('🔍 Admin - Error in setSessionPaymentStatus:', error)
    throw new Error(error.response?.data?.message || error.message || 'Failed to change payment status')
  }
}

// KAB-146: payment methods allowed to mark this session paid (resolved for a plate)
export const getSessionAllowedPaymentMethods = async (
  sessionId: string,
  licensePlate?: string
): Promise<{ status: string; message: string; data: { methods: SessionPaymentMethod[]; amount?: number; currency?: string } }> => {
  try {
    const query = licensePlate ? `?licensePlate=${encodeURIComponent(licensePlate)}` : ''
    const response = await api().get(`/api/charging-sessions/${sessionId}/payment-methods${query}`)
    if (response.data.status === 'error') {
      throw new Error(response.data.message)
    }
    return response.data
  } catch (error: any) {
    console.error('🔍 Admin - Error in getSessionAllowedPaymentMethods:', error)
    throw new Error(error.response?.data?.message || error.message || 'Failed to load payment methods')
  }
}

// KAB-146: session change history (audit trail)
export interface SessionHistoryEntry {
  id: string
  action: string
  changes: SessionAuditChange[]
  reason?: string
  oldLicensePlate?: string
  newLicensePlate?: string
  paymentMethod?: string
  paymentProofUrl?: string
  ebmRefunded: boolean
  ebmReissued: boolean
  performedBy: { id?: string; name?: string; email?: string }
  createdAt: string
}

export const getSessionHistory = async (
  sessionId: string
): Promise<{ status: string; message: string; data: { history: SessionHistoryEntry[] } }> => {
  try {
    const response = await api().get(`/api/charging-sessions/${sessionId}/history`)
    if (response.data.status === 'error') {
      throw new Error(response.data.message)
    }
    return response.data
  } catch (error: any) {
    console.error('🔍 Admin - Error in getSessionHistory:', error)
    throw new Error(error.response?.data?.message || error.message || 'Failed to load session history')
  }
}

// Delete charging session → move to archive (admin only). A reason is required.
export const deleteChargingSession = async (
  sessionId: string,
  reason: string,
): Promise<{ status: string; message: string; data?: { archiveId: string; airtableDeleted: boolean; airtableWarning?: string } }> => {
  try {
    const response = await api().delete(`/api/charging-sessions/${sessionId}`, { data: { reason } })

    if (response.data.status === 'error') {
      throw new Error(response.data.message)
    }

    return response.data
  } catch (error) {
    console.error('🔍 Admin - Error in deleteChargingSession:', error)
    throw error
  }
}

// Admin: manually create a charging session with full start-to-end info.
export interface CreateSessionPayload {
  chargerId: string
  gunId?: string
  operatorId: string
  vehicleId?: string
  licensePlate?: string
  startSoc: number
  endSoc?: number
  chargedKwh?: number
  startTime: string // ISO
  endTime?: string // ISO
  meterStart?: number
  meterEnd?: number
  ratePerKwh?: number
  totalAmount?: number
  sessionStatus?: 'STARTED' | 'PAUSED' | 'COMPLETED' | 'PAID' | 'EBM_ISSUED' | 'CANCELLED' | 'REFUNDED'
  customerName?: string
  customerPhone?: string
  carModelMake?: string
  description?: string
}

export const createSession = async (
  payload: CreateSessionPayload,
): Promise<{ status: string; message: string; data: { session: AdminSession } }> => {
  try {
    const response = await api().post('/api/charging-sessions/admin/create-session', payload)
    if (response.data.status === 'error') throw new Error(response.data.message)
    return response.data
  } catch (error: any) {
    console.error('🔍 Admin - Error in createSession:', error)
    throw new Error(error.response?.data?.message || error.message || 'Failed to create session')
  }
}

// Admin: archive (deleted sessions) — list + restore/undo.
export interface ArchivedSession {
  id: string
  originalSessionId: string
  sessionCode: string
  reason: string
  deletedAt: string
  deletedBy: { id: string | null; name: string; email: string | null }
  airtableDeleted: boolean
  airtableDeleteError: string | null
  session: {
    startTime: string | null
    endTime: string | null
    chargedKwh: number | null
    totalAmount: number | null
    sessionStatus: string | null
    customerName: string | null
  }
}

export interface ArchivedSessionsResult {
  items: ArchivedSession[]
  pagination: { page: number; limit: number; total: number; totalPages: number }
}

export const getArchivedSessions = async (
  params: { page?: number; limit?: number; search?: string } = {},
): Promise<{ status: string; message: string; data: ArchivedSessionsResult }> => {
  try {
    const response = await api().get('/api/charging-sessions/admin/archive', { params })
    if (response.data.status === 'error') throw new Error(response.data.message)
    return response.data
  } catch (error: any) {
    console.error('🔍 Admin - Error in getArchivedSessions:', error)
    throw new Error(error.response?.data?.message || error.message || 'Failed to load archived sessions')
  }
}

export const restoreArchivedSession = async (
  archiveId: string,
): Promise<{ status: string; message: string; data: { sessionId: string; sessionCode: string } }> => {
  try {
    const response = await api().post(`/api/charging-sessions/admin/archive/${archiveId}/restore`)
    if (response.data.status === 'error') throw new Error(response.data.message)
    return response.data
  } catch (error: any) {
    console.error('🔍 Admin - Error in restoreArchivedSession:', error)
    throw new Error(error.response?.data?.message || error.message || 'Failed to restore session')
  }
}

export interface PauseSessionPayload {
  reason?: string
}

export interface PauseSessionResponse {
  status: string
  message: string
  data: {
    session: AdminSession
    pausedBy?: string | null
    pauseReason?: string | null
  }
}

export interface ResumeSessionResponse {
  status: string
  message: string
  data: {
    session: AdminSession
    resumedBy?: string | null
  }
}

export interface CancelSessionPayload {
  reason: string
}

export interface CancelSessionResponse {
  status: string
  message: string
  data: {
    session: AdminSession & {
      cancellationReason?: string | null
      endTime?: string | null
    }
    cancelledBy?: string | null
  }
}

export interface UncancelSessionResponse {
  status: string
  message: string
  data: {
    session: AdminSession & {
      cancellationReason?: string | null
      endTime?: string | null
    }
    uncancelledBy?: string | null
  }
}

export const pauseChargingSession = async (
  sessionId: string,
  payload?: PauseSessionPayload
): Promise<PauseSessionResponse> => {
  try {
    const body = payload && payload.reason ? payload : {}
    const response = await api().post(`/api/charging-sessions/${sessionId}/pause`, body)

    if (response.data.status === 'error') {
      throw new Error(response.data.message)
    }

    return response.data
  } catch (error: any) {
    console.error('🔍 Admin - Error in pauseChargingSession:', error)
    throw new Error(error?.response?.data?.message || error.message || 'Failed to pause charging session')
  }
}

export const resumeChargingSession = async (sessionId: string): Promise<ResumeSessionResponse> => {
  try {
    const response = await api().post(`/api/charging-sessions/${sessionId}/resume`)

    if (response.data.status === 'error') {
      throw new Error(response.data.message)
    }

    return response.data
  } catch (error: any) {
    console.error('🔍 Admin - Error in resumeChargingSession:', error)
    throw new Error(error?.response?.data?.message || error.message || 'Failed to resume charging session')
  }
}

export const cancelChargingSession = async (
  sessionId: string,
  payload: CancelSessionPayload
): Promise<CancelSessionResponse> => {
  try {
    const response = await api().post(`/api/charging-sessions/${sessionId}/cancel`, payload)

    if (response.data.status === 'error') {
      throw new Error(response.data.message)
    }

    return response.data
  } catch (error: any) {
    console.error('🔍 Admin - Error in cancelChargingSession:', error)
    throw new Error(error?.response?.data?.message || error.message || 'Failed to cancel charging session')
  }
}

export const uncancelChargingSession = async (
  sessionId: string
): Promise<UncancelSessionResponse> => {
  try {
    const response = await api().post(`/api/charging-sessions/${sessionId}/uncancel`)

    if (response.data.status === 'error') {
      throw new Error(response.data.message)
    }

    return response.data
  } catch (error: any) {
    console.error('🔍 Admin - Error in uncancelChargingSession:', error)
    throw new Error(error?.response?.data?.message || error.message || 'Failed to uncancel charging session')
  }
}

// Admin: end a specific in-progress MANUAL session by id. Runs the full operator
// end pipeline server-side (pricing, payment, EBM); payment can then be settled with
// the payment-status tools if it lands COMPLETED+unpaid (e.g. MoMo).
export interface AdminEndSessionData {
  endSoc: number
  chargedKwh: number
  chargerScreen?: string
  carModelMake?: string
  ebmTin?: string
  purchaseCode?: string
  customerPhone?: string
  ebmCustomerName?: string
  ebmCustomerPhone?: string
  skipEbm?: boolean
  discountRate?: number
  discountAmount?: number
}

export const adminEndSession = async (
  sessionId: string,
  data: AdminEndSessionData
): Promise<{ status: string; message: string; data: unknown }> => {
  try {
    const response = await api().post(`/api/charging-sessions/${sessionId}/admin-end`, data)
    if (response.data.status === 'error') throw new Error(response.data.message)
    return response.data
  } catch (error: any) {
    console.error('🔍 Admin - Error in adminEndSession:', error)
    throw new Error(error.response?.data?.message || error.message || 'Failed to end session')
  }
}

// Admin: force-end an in-progress REMOTE session — bypasses the stale-sweep guard.
// Stops it on Citrine; if Citrine is unreachable, force-closes it locally.
export interface AdminForceEndRemoteResult {
  closedLocally: boolean
  session?: AdminSession | null
}

export const adminForceEndRemoteSession = async (
  sessionId: string,
  reason?: string
): Promise<{ status: string; message: string; data: AdminForceEndRemoteResult }> => {
  try {
    const response = await api().post(`/api/charging-sessions/${sessionId}/admin-force-end-remote`, reason ? { reason } : {})
    if (response.data.status === 'error') throw new Error(response.data.message)
    return response.data
  } catch (error: any) {
    console.error('🔍 Admin - Error in adminForceEndRemoteSession:', error)
    throw new Error(error.response?.data?.message || error.message || 'Failed to force-end session')
  }
}

// Admin: force-sync one session to Airtable now (instead of waiting for the sync job).
export interface SyncSessionAirtableResult {
  created: number
  updated: number
  airtableId: string | null
  syncedAt: string | null
  isSynced: boolean
}

export const syncSessionToAirtable = async (
  sessionId: string
): Promise<{ status: string; message: string; data: SyncSessionAirtableResult }> => {
  try {
    const response = await api().post(`/api/charging-sessions/${sessionId}/sync-airtable`)
    if (response.data.status === 'error') throw new Error(response.data.message)
    return response.data
  } catch (error: any) {
    console.error('🔍 Admin - Error in syncSessionToAirtable:', error)
    throw new Error(error.response?.data?.message || error.message || 'Failed to sync session to Airtable')
  }
}

// Check MOMO payment status for a charging session
export const checkMomoPaymentStatus = async (sessionId: string): Promise<{
  status: string
  message: string
  data: {
    sessionId: string
    sessionStatus: string
    isPaid: boolean
    message: string
    pendingCount: number
    checkedCount: number
    summary: {
      successful: number
      failed: number
      stillPending: number
    }
    results: Array<{
      transactionId: string
      amount: number
      currency: string
      status: string
      momoStatus: string
      reason: string
      checked: boolean
      isPaid: boolean
      error?: string
    }>
  }
}> => {
  try {
    const response = await api().get(`/api/charging-sessions/${sessionId}/momo-payment-status`)
    
    if (response.data.status === 'error') {
      throw new Error(response.data.message)
    }
    
    return response.data
  } catch (error) {
    console.error('🔍 Admin - Error in checkMomoPaymentStatus:', error)
    throw error
  }
}

// ===== KABISA ID MANAGEMENT APIs =====

// Create new Kabisa ID
export const createKabisaId = async (data: { kabisaId: string; kabisaIdType: 'CHARGER' | 'GUN' | 'METER' | 'VEHICLE' }): Promise<{ status: string; message: string; data: { kabisaId: any } }> => {
  try {
    const response = await api().post('/api/admin/kabisa-ids', data)
    
    if (response.data.status === 'error') {
      throw new Error(response.data.message)
    }
    
    return response.data
  } catch (error) {
    console.error('🔍 Admin - Error in createKabisaId:', error)
    throw error
  }
}

// Get all Kabisa IDs
export const getAllKabisaIds = async (): Promise<{ status: string; message: string; data: { kabisaIds: any[] } }> => {
  try {
    const response = await api().get('/api/admin/kabisa-ids')
    
    if (response.data.status === 'error') {
      throw new Error(response.data.message)
    }
    
    return response.data
  } catch (error) {
    console.error('🔍 Admin - Error in getAllKabisaIds:', error)
    throw error
  }
}

// Get unassigned Kabisa IDs
export const getUnassignedKabisaIds = async (): Promise<{ status: string; message: string; data: { kabisaIds: any[] } }> => {
  try {
    const response = await api().get('/api/admin/kabisa-ids/unassigned')
    
    if (response.data.status === 'error') {
      throw new Error(response.data.message)
    }
    
    return response.data
  } catch (error) {
    console.error('🔍 Admin - Error in getUnassignedKabisaIds:', error)
    throw error
  }
}

// Get assigned Kabisa IDs
export const getAssignedKabisaIds = async (): Promise<{ status: string; message: string; data: { kabisaIds: any[] } }> => {
  try {
    const response = await api().get('/api/admin/kabisa-ids/assigned')
    
    if (response.data.status === 'error') {
      throw new Error(response.data.message)
    }
    
    return response.data
  } catch (error) {
    console.error('🔍 Admin - Error in getAssignedKabisaIds:', error)
    throw error
  }
}

// Get Kabisa IDs by type
export const getKabisaIdsByType = async (type: 'CHARGER' | 'GUN' | 'METER' | 'VEHICLE'): Promise<{ status: string; message: string; data: { kabisaIds: any[] } }> => {
  try {
    const response = await api().get(`/api/admin/kabisa-ids/type/${type}`)
    
    if (response.data.status === 'error') {
      throw new Error(response.data.message)
    }
    
    return response.data
  } catch (error) {
    console.error('🔍 Admin - Error in getKabisaIdsByType:', error)
    throw error
  }
}

// Get specific Kabisa ID
export const getKabisaId = async (id: string): Promise<{ status: string; message: string; data: { kabisaId: any } }> => {
  try {
    const response = await api().get(`/api/admin/kabisa-ids/${id}`)
    
    if (response.data.status === 'error') {
      throw new Error(response.data.message)
    }
    
    return response.data
  } catch (error) {
    console.error('🔍 Admin - Error in getKabisaId:', error)
    throw error
  }
}

// Update Kabisa ID
export const updateKabisaId = async (id: string, data: Partial<{ kabisaId: string; kabisaIdType: 'CHARGER' | 'GUN' | 'METER' | 'VEHICLE' }>): Promise<{ status: string; message: string; data: { kabisaId: any } }> => {
  try {
    const response = await api().put(`/api/admin/kabisa-ids/${id}`, data)
    
    if (response.data.status === 'error') {
      throw new Error(response.data.message)
    }
    
    return response.data
  } catch (error) {
    console.error('🔍 Admin - Error in updateKabisaId:', error)
    throw error
  }
}

// Delete (deactivate) Kabisa ID
export const deleteKabisaId = async (id: string): Promise<{ status: string; message: string }> => {
  try {
    const response = await api().delete(`/api/admin/kabisa-ids/${id}`)
    
    if (response.data.status === 'error') {
      throw new Error(response.data.message)
    }
    
    return response.data
  } catch (error) {
    console.error('🔍 Admin - Error in deleteKabisaId:', error)
    throw error
  }
}

// Assign Kabisa ID to entity
export const assignKabisaId = async (id: string, data: { entityId: string; entityType: 'CHARGER' | 'GUN' | 'METER' | 'VEHICLE' }): Promise<{ status: string; message: string; data: { kabisaId: any } }> => {
  try {
    const response = await api().post(`/api/admin/kabisa-ids/${id}/assign`, data)
    
    if (response.data.status === 'error') {
      throw new Error(response.data.message)
    }
    
    return response.data
  } catch (error) {
    console.error('🔍 Admin - Error in assignKabisaId:', error)
    throw error
  }
}

// Unassign Kabisa ID
export const unassignKabisaId = async (id: string): Promise<{ status: string; message: string; data: { kabisaId: any } }> => {
  try {
    const response = await api().post(`/api/admin/kabisa-ids/${id}/unassign`)
    
    if (response.data.status === 'error') {
      throw new Error(response.data.message)
    }
    
    return response.data
  } catch (error) {
    console.error('🔍 Admin - Error in unassignKabisaId:', error)
    throw error
  }
}

// Get single charger (returns charger + pedestals with guns)
export const getCharger = async (chargerId: string): Promise<{ status: string; message: string; data: { charger: Charger; pedestals: Pedestal[] } }> => {
  try {
    const response = await api().get(`/api/chargers/${chargerId}`)
    if (response.data.status === 'error') {
      throw new Error(response.data.message)
    }
    return response.data
  } catch (error) {
    console.error('🔍 Admin - Error in getCharger:', error)
    throw error
  }
}

/** Get charger with guns – uses getCharger and flattens guns from pedestals for compatibility */
export const getChargerWithGuns = async (chargerId: string): Promise<{ status: string; message: string; data: { charger: Charger; guns: Gun[]; pedestals: Pedestal[] } }> => {
  const result = await getCharger(chargerId)
  // Guns may be nested under pedestals (detail endpoint) or appear at top-level (flattened list responses)
  const chargerForGuns: Charger = { ...result.data.charger, pedestals: result.data.pedestals }
  const guns = getChargerGuns(chargerForGuns)
  return {
    ...result,
    data: { ...result.data, guns }
  }
}

// Add pedestal to charger
export const addPedestalToCharger = async (chargerId: string, data: PedestalCreateData): Promise<{ status: string; message: string; data: { pedestal: Pedestal } }> => {
  try {
    const response = await api().post(`/api/chargers/${chargerId}/pedestals`, data)
    if (response.data.status === 'error') throw new Error(response.data.message)
    return response.data
  } catch (error) {
    console.error('Admin - Error in addPedestalToCharger:', error)
    throw error
  }
}

// Update pedestal
export const updatePedestal = async (pedestalId: string, data: PedestalUpdateData): Promise<{ status: string; message: string; data: { pedestal: Pedestal } }> => {
  try {
    const response = await api().put(`/api/chargers/pedestals/${pedestalId}`, data)
    if (response.data.status === 'error') {
      throw new Error(response.data.message)
    }
    return response.data
  } catch (error) {
    console.error('🔍 Admin - Error in updatePedestal:', error)
    throw error
  }
}

// ===== Gun Management API Functions =====

// Add gun to charger
export const addGunToCharger = async (chargerId: string, data: GunCreateData): Promise<{ status: string; message: string; data: { gun: Gun } }> => {
  try {
    const response = await api().post(`/api/chargers/${chargerId}/guns`, data)
    
    if (response.data.status === 'error') {
      throw new Error(response.data.message)
    }
    
    return response.data
  } catch (error) {
    console.error('🔍 Admin - Error in addGunToCharger:', error)
    throw error
  }
}

// Update gun
export const updateGun = async (chargerId: string, gunId: string, data: GunUpdateData): Promise<{ status: string; message: string; data: { gun: Gun } }> => {
  try {
    const response = await api().put(`/api/chargers/${chargerId}/guns/${gunId}`, data)
    
    if (response.data.status === 'error') {
      throw new Error(response.data.message)
    }
    
    return response.data
  } catch (error) {
    console.error('🔍 Admin - Error in updateGun:', error)
    throw error
  }
}

// Update gun status
export const updateGunStatus = async (gunId: string, data: GunStatusUpdateData): Promise<{ status: string; message: string; data: { gun: Gun } }> => {
  try {
    const response = await api().put(`/api/chargers/guns/${gunId}/status`, data)
    if (response.data.status === 'error') {
      throw new Error(response.data.message)
    }
    return response.data
  } catch (error) {
    console.error('🔍 Admin - Error in updateGunStatus:', error)
    throw error
  }
}

// Delete gun (reassign sessions to target gun)
export const deleteGun = async (gunId: string, targetGunId: string): Promise<{ status: string; message: string }> => {
  try {
    const response = await api().delete(`/api/chargers/guns/${gunId}`, { data: { targetGunId } })
    if (response.data.status === 'error') {
      throw new Error(response.data.message)
    }
    return response.data
  } catch (error) {
    console.error('Error in deleteGun:', error)
    throw error
  }
}

// Delete pedestal (reassign sessions to target pedestal if provided)
export const deletePedestal = async (pedestalId: string, targetPedestalId?: string | null): Promise<{ status: string; message: string }> => {
  try {
    const response = await api().delete(`/api/chargers/pedestals/${pedestalId}`, { data: targetPedestalId ? { targetPedestalId } : {} })
    if (response.data.status === 'error') {
      throw new Error(response.data.message)
    }
    return response.data
  } catch (error) {
    console.error('Error in deletePedestal:', error)
    throw error
  }
}

// ===== Meter management (charger-related) =====

export const createMeter = async (data: MeterCreateData): Promise<{ status: string; message: string; data: { meter: Meter } }> => {
  try {
    const response = await api().post('/api/chargers/meters', data)
    if (response.data.status === 'error') {
      throw new Error(response.data.message)
    }
    return response.data
  } catch (error) {
    console.error('🔍 Admin - Error in createMeter:', error)
    throw error
  }
}

export const updateChargerMeter = async (chargerId: string, data: { meterId?: string }): Promise<{ status: string; message: string }> => {
  try {
    const response = await api().put(`/api/chargers/${chargerId}/meter`, data)
    if (response.data.status === 'error') {
      throw new Error(response.data.message)
    }
    return response.data
  } catch (error) {
    console.error('🔍 Admin - Error in updateChargerMeter:', error)
    throw error
  }
}

export const getChargerMeter = async (chargerId: string): Promise<{ status: string; message: string; data: unknown }> => {
  try {
    const response = await api().get(`/api/chargers/${chargerId}/meter`)
    if (response.data.status === 'error') {
      throw new Error(response.data.message)
    }
    return response.data
  } catch (error) {
    console.error('🔍 Admin - Error in getChargerMeter:', error)
    throw error
  }
}

export const getAllChargerMeters = async (): Promise<{ status: string; message: string; data: { meters?: Meter[] } }> => {
  try {
    const response = await api().get('/api/chargers/meters/all')
    if (response.data.status === 'error') {
      throw new Error(response.data.message)
    }
    return response.data
  } catch (error) {
    console.error('🔍 Admin - Error in getAllChargerMeters:', error)
    throw error
  }
}

// ===== VSDC Initialization APIs =====

// Get VSDC status
export const getVsdcStatus = async (): Promise<{ success: boolean; message: string; data: { online: boolean; responseTime?: number } }> => {
  try {
    const response = await api().get('/api/ebm/vsdc/status')
    return response.data
  } catch (error) {
    console.error('Admin - Error in getVsdcStatus:', error)
    throw error
  }
}

// Initialize VSDC
export const initializeVsdc = async (tin: string, bhfId: string, dvcSrlNo: string): Promise<{ success: boolean; message: string; data: any }> => {
  try {
    const response = await api().post('/api/ebm/vsdc/initialize', { tin, bhfId, dvcSrlNo })
    return response.data
  } catch (error) {
    console.error('Admin - Error in initializeVsdc:', error)
    throw error
  }
}

// ===== Session EBM Info API Functions =====

export interface SessionEBMInfo {
  ebmTin: string | null
  purchaseCode: string | null
  customerPhone: string | null
  ebmPaymentMethodCode: string | null
  ebmPaymentMethodName: string | null
}

export interface UpdateSessionEBMInfoData {
  ebmTin?: string | null
  purchaseCode?: string | null
  customerPhone?: string | null
  ebmPaymentMethodCode?: string | null
  ebmPaymentMethodName?: string | null
}

// Get session EBM info
export const getSessionEBMInfo = async (sessionId: string): Promise<{ status: string; message: string; data: { ebmInfo: SessionEBMInfo } }> => {
  try {
    const response = await api().get(`/api/charging-sessions/${sessionId}/ebm-info`)
    
    if (response.data.status === 'error') {
      throw new Error(response.data.message)
    }
    
    return response.data
  } catch (error) {
    console.error('🔍 Admin - Error in getSessionEBMInfo:', error)
    throw error
  }
}

// Update session EBM info
export const updateSessionEBMInfo = async (sessionId: string, data: UpdateSessionEBMInfoData): Promise<{ status: string; message: string; data: { ebmInfo: SessionEBMInfo } }> => {
  try {
    const response = await api().patch(`/api/charging-sessions/${sessionId}/ebm-info`, data)
    
    if (response.data.status === 'error') {
      throw new Error(response.data.message)
    }
    
    return response.data
  } catch (error) {
    console.error('🔍 Admin - Error in updateSessionEBMInfo:', error)
    throw error
  }
}

// ===== CIS / VSDC Codes Sync API Functions =====

export interface VsdcCodesSyncPayload {
  fullSync?: boolean
  since?: string
}

export interface VsdcCodesSyncData {
  classesCreated?: number
  classesUpdated?: number
  detailsCreated?: number
  detailsUpdated?: number
  resultDt?: string
  errors?: string[]
}

export interface VsdcCodesSyncResponse {
  success: boolean
  message: string
  data?: VsdcCodesSyncData
}

export const syncVsdcCodes = async (
  payload: VsdcCodesSyncPayload = {}
): Promise<VsdcCodesSyncResponse> => {
  try {
    const response = await api().post('/api/ebm/codes/sync', payload)
    return response.data as VsdcCodesSyncResponse
  } catch (error) {
    console.error('🔍 Admin - Error in syncVsdcCodes:', error)
    throw error
  }
}

export interface VsdcCodeItem {
  code: string
  name: string
}

export interface VsdcCurrentCodes {
  paymentMethods: VsdcCodeItem[]
  refundReasons: VsdcCodeItem[]
  salesTypes: VsdcCodeItem[]
  receiptTypes: VsdcCodeItem[]
}

export interface VsdcCurrentCodesResponse {
  success: boolean
  message: string
  data: VsdcCurrentCodes
}

export const getCurrentVsdcCodes = async (): Promise<VsdcCurrentCodesResponse> => {
  try {
    const response = await api().get('/api/ebm/codes/current')
    return response.data as VsdcCurrentCodesResponse
  } catch (error) {
    console.error('🔍 Admin - Error in getCurrentVsdcCodes:', error)
    throw error
  }
}

// ===========================================================================
// Citrine Observability
// ===========================================================================

export interface CitrineLatencyBucket {
  count: number
  p50: number | null
  p95: number | null
  p99: number | null
  max: number | null
}

export interface CitrineCounters {
  rowsReceivedLifecycle: number
  rowsReceivedTelemetry: number
  transitionsHandled: number
  startHandled: number
  endHandled: number
  orphanCreated: number
  telemetryFlushed: number
  telemetryDropped: number
  writeBackEnqueued: number
  writeBackSucceeded: number
  writeBackFailed: number
  writeBackRetries: number
  wsConnects: number
  wsDisconnects: number
  reconnectAttempts: number
  staleClosed: number
  errors: number
}

export interface CitrineTelemetryGauges {
  activeTxCount: number
  debouncedTxCount: number
  pedestalGunCacheSize: number
  operatorShiftCacheSize: number
}

export interface CitrineStatusData {
  connected: boolean
  wsConnectedAt: string | null
  lastRowAt: string | null
  lastStartAt: string | null
  lastEndAt: string | null
  counters: CitrineCounters
  latency: {
    start: CitrineLatencyBucket
    end: CitrineLatencyBucket
    startHandler: CitrineLatencyBucket
    endHandler: CitrineLatencyBucket
    telemetryFlush: CitrineLatencyBucket
    writeBackRoundTrip: CitrineLatencyBucket
  }
  eventTotal: number
  eventRingSize: number
  telemetry: CitrineTelemetryGauges
  writeBackQueueDepth: number
}

export type CitrineEventKind =
  | 'row-received'
  | 'start-handled'
  | 'end-handled'
  | 'telemetry-flushed'
  | 'orphan-created'
  | 'ws-connected'
  | 'ws-disconnected'
  | 'write-back-failed'
  | 'stale-close'
  | 'error'

export interface CitrineEvent {
  ts: string
  kind: CitrineEventKind
  citrineSourceId?: number
  sessionId?: string
  message?: string
  meta?: Record<string, unknown>
}

export interface CitrineStatusResponse {
  status: 'success' | 'error'
  message: string
  data: CitrineStatusData
}

export interface CitrineEventsResponse {
  status: 'success' | 'error'
  message: string
  data: {
    limit: number
    events: CitrineEvent[]
  }
}

export const getCitrineStatus = async (): Promise<CitrineStatusData> => {
  try {
    const response = await api(false, false).get('/api/admin/citrine/status')
    const body = response.data as CitrineStatusResponse
    if (body?.status === 'error') throw new Error(body.message || 'Citrine status error')
    return body.data
  } catch (error) {
    console.error('🔍 Admin - Error in getCitrineStatus:', error)
    throw error
  }
}

export const getCitrineEvents = async (limit = 100): Promise<CitrineEvent[]> => {
  const clamped = Math.max(1, Math.min(500, Math.floor(limit)))
  try {
    const response = await api(false, false).get(`/api/admin/citrine/events?limit=${clamped}`)
    const body = response.data as CitrineEventsResponse
    if (body?.status === 'error') throw new Error(body.message || 'Citrine events error')
    return body.data.events
  } catch (error) {
    console.error('🔍 Admin - Error in getCitrineEvents:', error)
    throw error
  }
}
