import {
    Home,
    Users2,
    ClipboardList,
    QrCode,
    LayoutDashboard,
    BatteryCharging,
    LogIn,
    LogOut,
    Timer,
    Car,
    PlusCircle,
    CarFront,
    Store,
    Building2,
    PlugZap,
    Battery,
    Box,
    RefreshCw,
    Mail,
    IdCard,
    History,
    Wallet,
    CreditCard,
    Star,
    Settings,
    UserPlus,
    FileText,
    BarChart3,
    User,
    Package,
    Receipt,
    Globe,
    RadioTower
} from "lucide-react";
import { UserRole } from "@/lib/utils/roleRedirect";
import { MenuItem } from "@/types/sidebar";

export const ALL_MENU_ITEMS: MenuItem[] = [
    // Dashboard - Available for all roles
    {
        id: "dashboard",
        title: "Dashboard",
        path: "/dashboard",
        icon: Home,
        roles: [UserRole.CUSTOMER, UserRole.OPERATOR, UserRole.ORGANIZATION_ADMIN, UserRole.ADMIN],
        scope: "any",
    },

    // Personal Customer Menu Items (Available to all customers)
    {
        id: "customerVehicles",
        title: "My Vehicles",
        path: "/dashboard/customer/vehicles",
        icon: Car,
        roles: [UserRole.CUSTOMER],
        scope: "personal",
    },
    {
        id: "customerSessions",
        title: "My Sessions",
        path: "/dashboard/customer/sessions",
        icon: History,
        roles: [UserRole.CUSTOMER],
        scope: "personal",
    },
    {
        id: "customerEntitlements",
        title: "Entitlements",
        path: "/dashboard/customer/entitlements",
        icon: Star,
        roles: [UserRole.CUSTOMER],
        scope: "personal",
    },
    {
        id: "customerPayments",
        title: "Payment Methods",
        path: "/dashboard/customer/payments",
        icon: CreditCard,
        roles: [UserRole.CUSTOMER],
        scope: "personal",
    },
    {
        id: "pendingInvitations",
        title: "Pending Invitations",
        path: "/dashboard/invitations",
        icon: Mail,
        roles: [UserRole.CUSTOMER],
        scope: "any",
    },

    // Business Management - Customer Menu Items (Hidden for invited users and drivers)
    {
        id: "businessManagement",
        title: "Business Management",
        icon: Building2,
        roles: [UserRole.CUSTOMER],
        scope: "business",
        submenu: [
            {
                id: "createBusiness",
                title: "Create Business",
                path: "/dashboard/customer/business/create",
                icon: PlusCircle,
                roles: [UserRole.CUSTOMER],
                scope: "business",
                businessRoles: ["OWNER"], // Only business owners can create businesses
            },
            {
                id: "teamManagement",
                title: "Team Management",
                path: "/dashboard/customer/business/team",
                icon: Users2,
                roles: [UserRole.CUSTOMER],
                scope: "business",
                businessRoles: ["OWNER", "FINANCE"], // Owners and finance can manage team
            },
            {
                id: "businessInvitations",
                title: "Manage Invitations",
                path: "/dashboard/customer/business/invitations",
                icon: Mail,
                roles: [UserRole.CUSTOMER],
                scope: "business",
                businessRoles: ["OWNER", "FINANCE"], // Only owners and finance can send invitations
            },
            {
                id: "fleetManagement",
                title: "Fleet Management",
                path: "/dashboard/customer/business/fleet",
                icon: Car,
                roles: [UserRole.CUSTOMER],
                scope: "business",
                businessRoles: ["OWNER", "FINANCE"], // Only owners and finance can manage fleet
            },
            {
                id: "businessContracts",
                title: "Business Contracts",
                path: "/dashboard/customer/business/contracts",
                icon: FileText,
                roles: [UserRole.CUSTOMER],
                scope: "business",
                businessRoles: ["OWNER", "FINANCE"], // Only owners and finance can view contracts
            },
            {
                id: "assignedVehicles",
                title: "My Assigned Vehicles",
                path: "/dashboard/customer/business/assigned-vehicles",
                icon: Car,
                roles: [UserRole.CUSTOMER],
                scope: "business",
                businessRoles: ["DRIVER"], // Only drivers see this
            },
            {
                id: "driverSessions",
                title: "My Sessions",
                path: "/dashboard/customer/business/driver-sessions",
                icon: History,
                roles: [UserRole.CUSTOMER],
                scope: "business",
                businessRoles: ["DRIVER"], // Only drivers see this
            },
           
        ],
    },

    // Operator Menu Items
    {
        id: "chargingSession",
        title: "Charging Session",
        icon: BatteryCharging,
        roles: [UserRole.OPERATOR, UserRole.ORGANIZATION_ADMIN, UserRole.ADMIN],
        scope: "any",
        submenu: [
            {
                id: "sessionStart",
                title: "Start Session",
                path: "/dashboard/charge/session?op=start",
                icon: LogIn,
                roles: [UserRole.OPERATOR, UserRole.ORGANIZATION_ADMIN, UserRole.ADMIN],
                scope: "any",
            },
            {
                id: "sessionEnd",
                title: "End Session",
                path: "/dashboard/charge/session?op=end",
                icon: LogOut,
                roles: [UserRole.OPERATOR, UserRole.ORGANIZATION_ADMIN, UserRole.ADMIN],
                scope: "any",
            },
        ],
    },
    {
        id: "scan",
        title: "Scan",
        path: "/dashboard/scan",
        icon: QrCode,
        roles: [UserRole.OPERATOR, UserRole.ORGANIZATION_ADMIN, UserRole.ADMIN],
        scope: "any",
    },
    {
        id: "sessions",
        title: "Sessions",
        path: "/dashboard/charge/sessions",
        icon: History,
        roles: [UserRole.OPERATOR, UserRole.ORGANIZATION_ADMIN, UserRole.ADMIN],
        scope: "any",
    },
    {
        id: "shift",
        title: "My Shifts",
        icon: Timer,
        path: "/dashboard/shifts",
        roles: [UserRole.OPERATOR],
        scope: "any",
    },
    {
        id: "inspect",
        title: "Inspect",
        icon: ClipboardList,
        roles: [UserRole.OPERATOR, UserRole.ORGANIZATION_ADMIN, UserRole.ADMIN],
        path: "/dashboard/charge/inspect",
        scope: "any",
    },

    // Organization Admin Menu Items
    {
        id: "orgManagement",
        title: "Organization",
        icon: Building2,
        roles: [UserRole.ORGANIZATION_ADMIN],
        scope: "any",
        submenu: [
            {
                id: "orgChargers",
                title: "Chargers",
                path: "/dashboard/org-admin/chargers",
                icon: Battery,
                roles: [UserRole.ORGANIZATION_ADMIN],
                scope: "any",
            },
            {
                id: "orgMembers",
                title: "Members",
                path: "/dashboard/org-admin/members",
                icon: Users2,
                roles: [UserRole.ORGANIZATION_ADMIN],
                scope: "any",
            },
            {
                id: "orgSessions",
                title: "All Sessions",
                path: "/dashboard/org-admin/sessions",
                icon: History,
                roles: [UserRole.ORGANIZATION_ADMIN],
                scope: "any",
            },
            {
                id: "orgShifts",
                title: "Shifts",
                path: "/dashboard/org-admin/shifts",
                icon: Timer,
                roles: [UserRole.ORGANIZATION_ADMIN],
                scope: "any",
            },
        ],
    },

    // Admin menu groups shown directly at top-level (no "Admin" parent).
    {
        id: "adminEbm",
        title: "EBM",
        icon: Receipt,
        roles: [UserRole.ADMIN],
        scope: "any",
        submenu: [
            {
                id: "standaloneProforma",
                title: "Proforma EBM",
                path: "/dashboard/admin/standalone-proforma",
                icon: Receipt,
                roles: [UserRole.ADMIN],
                scope: "any",
            },
            {
                id: "missingEbm",
                title: "Missing EBM",
                path: "/dashboard/admin/missing-ebm",
                icon: Receipt,
                roles: [UserRole.ADMIN],
                scope: "any",
            },
            {
                id: "failedEbm",
                title: "Failed EBM",
                path: "/dashboard/admin/failed-ebm",
                icon: Receipt,
                roles: [UserRole.ADMIN],
                scope: "any",
            },
            {
                id: "pluReports",
                title: "PLU Report",
                path: "/dashboard/admin/plu-reports",
                icon: FileText,
                roles: [UserRole.ADMIN],
                scope: "any",
            },
            {
                id: "xzReports",
                title: "X/Z Reports",
                path: "/dashboard/admin/xz-reports",
                icon: BarChart3,
                roles: [UserRole.ADMIN],
                scope: "any",
            },
            {
                id: "salesReports",
                title: "Sales Report",
                path: "/dashboard/admin/sales-reports",
                icon: Receipt,
                roles: [UserRole.ADMIN],
                scope: "any",
            },
        ],
    },
    {
        id: "adminEbmConfig",
        title: "EBM Config",
        icon: Settings,
        roles: [UserRole.ADMIN],
        scope: "any",
        submenu: [
            {
                id: "ebmConfig",
                title: "EBM Configuration",
                path: "/dashboard/admin/ebm-config",
                icon: FileText,
                roles: [UserRole.ADMIN],
                scope: "any",
            },
            {
                id: "ebmItems",
                title: "EBM Items",
                path: "/dashboard/admin/ebm-items",
                icon: Package,
                roles: [UserRole.ADMIN],
                scope: "any",
            },
            {
                id: "ebmCodesSync",
                title: "CIS / VSDC Codes sync",
                path: "/dashboard/admin/ebm-codes-sync",
                icon: RefreshCw,
                roles: [UserRole.ADMIN],
                scope: "any",
            },
            {
                id: "vsdcInit",
                title: "VSDC Initialization",
                path: "/dashboard/admin/vsdc-init",
                icon: Settings,
                roles: [UserRole.ADMIN],
                scope: "any",
            },
        ],
    },
    {
        id: "adminShifts",
        title: "Shifts",
        icon: Timer,
        roles: [UserRole.ADMIN],
        scope: "any",
        submenu: [
            {
                id: "shifts",
                title: "Shift Management",
                path: "/dashboard/admin/shifts",
                icon: Timer,
                roles: [UserRole.ADMIN],
                scope: "any",
            },
            {
                id: "shiftReports",
                title: "Shift Reports",
                path: "/dashboard/admin/shifts/reports",
                icon: BarChart3,
                roles: [UserRole.ADMIN],
                scope: "any",
            },
        ],
    },
    {
        id: "adminUsersAccess",
        title: "Users & Access",
        icon: Users2,
        roles: [UserRole.ADMIN],
        scope: "any",
        submenu: [
            {
                id: "users",
                title: "Users",
                path: "/dashboard/admin/users",
                icon: Users2,
                roles: [UserRole.ADMIN],
                scope: "any",
            },
            {
                id: "organizations",
                title: "Organizations",
                path: "/dashboard/admin/organizations",
                icon: Building2,
                roles: [UserRole.ADMIN],
                scope: "any",
            },
            {
                id: "kabisaIds",
                title: "Kabisa IDs",
                path: "/dashboard/admin/kabisa-ids",
                icon: IdCard,
                roles: [UserRole.ADMIN],
                scope: "any",
            },
            {
                id: "countries",
                title: "Countries",
                path: "/dashboard/admin/countries",
                icon: Globe,
                roles: [UserRole.ADMIN],
                scope: "any",
            },
        ],
    },
    {
        id: "adminFleet",
        title: "Fleet",
        icon: Car,
        roles: [UserRole.ADMIN],
        scope: "any",
        submenu: [
            {
                id: "individualVehicles",
                title: "Individual Vehicles",
                path: "/dashboard/admin/individual-vehicles",
                icon: Car,
                roles: [UserRole.ADMIN],
                scope: "any",
            },
            {
                id: "shopVehicles",
                title: "Shop Vehicles",
                path: "/dashboard/admin/shop-vehicles",
                icon: Store,
                roles: [UserRole.ADMIN],
                scope: "any",
            },
            {
                id: "businesses",
                title: "Business Management",
                path: "/dashboard/admin/businesses",
                icon: Building2,
                roles: [UserRole.ADMIN],
                scope: "any",
            },
        ],
    },
    {
        id: "adminChargers",
        title: "Chargers",
        icon: Battery,
        roles: [UserRole.ADMIN],
        scope: "any",
        submenu: [
            {
                id: "chargers",
                title: "Chargers",
                path: "/dashboard/admin/chargers",
                icon: Battery,
                roles: [UserRole.ADMIN],
                scope: "any",
            },
            {
                id: "citrineObservability",
                title: "Citrine Sync",
                path: "/dashboard/admin/citrine",
                icon: RadioTower,
                roles: [UserRole.ADMIN],
                scope: "any",
            },
        ],
    },

    // Profile - Available for all roles
    {
        id: "profile",
        title: "Profile",
        path: "/dashboard/profile",
        icon: User,
        roles: [UserRole.CUSTOMER, UserRole.OPERATOR, UserRole.ORGANIZATION_ADMIN, UserRole.ADMIN],
        scope: "any",
    },

    // Settings - Available for all roles
    {
        id: "settings",
        title: "Settings",
        path: "/dashboard/settings",
        icon: Settings,
        roles: [UserRole.CUSTOMER, UserRole.OPERATOR, UserRole.ORGANIZATION_ADMIN, UserRole.ADMIN],
        scope: "any",
    },
];
